select*from customer;
select age,gender from customer;



-- Q1. What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avg_review_rating
from customer 
group by item_purchased
order by avg_review_rating desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping?   
select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount 
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do Subscribed cusomers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 
select subscription_status, 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round((sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) * 100),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as (
select previous_purchases,
case 
 when previous_purchases = 1 then 'New'
 when previous_purchases between 1 and 10 then 'Returning'
 else 'Loyal' 
 end as customer_segment
from customer
)
select customer_segment, count(*) as 'Number Of Customers'
from customer_type
group by customer_segment;

-- Q8. What are the top3 most purchased products within each category? 
with products as (
select category, 
item_purchased,
count(item_purchased) as most_purchased_products,
row_number() over (partition by category order by count(item_purchased) desc) as item_rnk
from customer
group by category, item_purchased
)
select category, item_purchased, most_purchased_products, item_rnk
from products 
where item_rnk <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)	also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
